module.exports = {
    IS_AUTHENTICATING: 'is_authenticating',
    AUTHENTICATE_USER: 'authenticate_user',
    AUTHENTICATION_ERROR: 'authentication_error',
    IS_REGISTERING: 'is_registering',
    REGISTER_USER: 'register_user',
    REGISTRATION_ERROR: 'registration_error',
    SUBMIT_IN_PROGRESS: 'submit_in_progress',
    ADD_NEW_CRYPTO_SUCCESS: 'add_new_crypto_success',
    ADD_NEW_CRYPTO_ERR: 'add_new_crypto_err',
    GET_SYMBOL_LIST: 'get_symbol_list',
    GET_BUY_ORDER_LIST: 'get_buy_order_list',
    GET_SELL_ORDER_LIST: 'get_sell_order_list',
    GET_FIAT_OPTION_LIST: 'get_fiat_option_list',
    GET_USER_SETTINGS_LIST: 'get_user_settings_list',
    GET_PROFIT_LOSS_TRANSACTION_LIST: 'get_profit_loss_transaction_list',
    GET_REFINED_PROFIT_LOSS_TRANSACTION_LIST: 'get_refined_profit_loss_transaction_list',
    GET_CRYPTO_ASSET_LIST: 'get_crypto_asset_list',
    GET_COIN_MARKET_API_DATA: 'get_coin_market_api_data'
}