# Generated by Django 2.0.1 on 2018-03-28 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('purchase_price_btc', models.DecimalField(decimal_places=6, max_digits=19)),
                ('purchase_price_fiat', models.DecimalField(decimal_places=6, max_digits=19)),
                ('exchange_fee_btc', models.DecimalField(decimal_places=6, max_digits=19)),
                ('exchange_fee_fiat', models.DecimalField(decimal_places=6, max_digits=19)),
                ('sell_order_fulfilled', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitLossTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity_sold', models.DecimalField(decimal_places=6, max_digits=19)),
                ('total_buy_price_btc', models.DecimalField(decimal_places=6, max_digits=19)),
                ('total_buy_price_fiat', models.DecimalField(decimal_places=6, max_digits=19)),
                ('total_sell_price_btc', models.DecimalField(decimal_places=6, max_digits=19)),
                ('total_sell_price_fiat', models.DecimalField(decimal_places=6, max_digits=19)),
                ('exchange_fee_btc', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('exchange_fee_fiat', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('gain_loss_percentage', models.DecimalField(decimal_places=6, max_digits=19)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.BuyOrder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('sell_price_btc', models.DecimalField(decimal_places=6, max_digits=19)),
                ('sell_price_fiat', models.DecimalField(decimal_places=6, max_digits=19)),
                ('exchange_fee_btc', models.DecimalField(decimal_places=6, max_digits=19)),
                ('exchange_fee_fiat', models.DecimalField(decimal_places=6, max_digits=19)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
