# Generated by Django 2.0.1 on 2018-03-31 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=7)),
                ('flag_image', models.ImageField(blank=True, null=True, upload_to='flags/')),
            ],
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='fiat_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.FiatOption'),
        ),
    ]
